// Generated by gencpp from file beginner_tutorials_tan/AddTwoInt.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_TAN_MESSAGE_ADDTWOINT_H
#define BEGINNER_TUTORIALS_TAN_MESSAGE_ADDTWOINT_H

#include <ros/service_traits.h>


#include <beginner_tutorials_tan/AddTwoIntRequest.h>
#include <beginner_tutorials_tan/AddTwoIntResponse.h>


namespace beginner_tutorials_tan
{

struct AddTwoInt
{

typedef AddTwoIntRequest Request;
typedef AddTwoIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInt
} // namespace beginner_tutorials_tan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials_tan::AddTwoInt > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials_tan::AddTwoInt&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials_tan::AddTwoInt > {
  static const char* value()
  {
    return "beginner_tutorials_tan/AddTwoInt";
  }

  static const char* value(const ::beginner_tutorials_tan::AddTwoInt&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials_tan::AddTwoIntRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials_tan::AddTwoInt >
template<>
struct MD5Sum< ::beginner_tutorials_tan::AddTwoIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials_tan::AddTwoInt >::value();
  }
  static const char* value(const ::beginner_tutorials_tan::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials_tan::AddTwoIntRequest> should match
// service_traits::DataType< ::beginner_tutorials_tan::AddTwoInt >
template<>
struct DataType< ::beginner_tutorials_tan::AddTwoIntRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials_tan::AddTwoInt >::value();
  }
  static const char* value(const ::beginner_tutorials_tan::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials_tan::AddTwoIntResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials_tan::AddTwoInt >
template<>
struct MD5Sum< ::beginner_tutorials_tan::AddTwoIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials_tan::AddTwoInt >::value();
  }
  static const char* value(const ::beginner_tutorials_tan::AddTwoIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials_tan::AddTwoIntResponse> should match
// service_traits::DataType< ::beginner_tutorials_tan::AddTwoInt >
template<>
struct DataType< ::beginner_tutorials_tan::AddTwoIntResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials_tan::AddTwoInt >::value();
  }
  static const char* value(const ::beginner_tutorials_tan::AddTwoIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_TAN_MESSAGE_ADDTWOINT_H
